import { Metadata } from 'next'

import './privacy.css'

export default function PrivacyPage() {
  return (
    <div className="max-w-6xl mx-auto">
      <h1>Privacy Policy</h1>
      <p>Effective date: 07/01/2025</p>
      <h2>1. Introduction</h2>
      <p>
        Welcome to Mapped! Mapped is developed and maintained by Common
        Knowledge, a not-for-profit worker cooperative of technologists,
        designers, researchers and facilitators. We work in direct collaboration
        with grassroots organisers and communities around the world, using our
        digital expertise to multiply their impact and capacity.
      </p>
      <p>
        Common Knowledge Cooperative Limited (“us”, “we”, or “our”) operates
        https://mapped.tools (hereinafter referred to as “Service”).
      </p>
      <p>
        Our Privacy Policy governs your visit to https://mapped.tools and
        explains how we collect, safeguard and disclose information that results
        from your use of our Service.
      </p>
      <p>
        We use your data to provide and improve Service. By using Service, you
        agree to the collection and use of information in accordance with this
        policy. Unless otherwise defined in this Privacy Policy, the terms used
        in this Privacy Policy have the same meanings as in our Terms and
        Conditions.
      </p>
      <p>
        Our Terms of Service (“Terms”) govern all use of our Service and
        together with the Privacy Policy constitutes your agreement with us
        (“agreement”).
      </p>
      <h2>2. Definitions</h2>
      <p>
        <strong>SERVICE</strong> means the
        https://prototype.mapped.commonknowledge.coop/ website operated by
        Common Knowledge Cooperative Limited.
      </p>
      <p>
        <strong>PERSONAL DATA</strong> means data about a living individual who
        can be identified from those data (or from those and other information
        either in our possession or likely to come into our possession).
      </p>
      <p>
        <strong>USAGE DATA</strong> is data collected automatically either
        generated by the use of Service or from Service infrastructure itself
        (for example, the duration of a page visit).
      </p>
      <p>
        <strong>COOKIES</strong> are small files stored on your device (computer
        or mobile device).
      </p>
      <p>
        <strong>DATA CONTROLLER</strong> means a natural or legal person, public
        authority, agency or other body which, alone or jointly with others,
        determines the purposes and means of the processing of personal data.
        For the purpose of this Privacy Policy, we are a Data Controller of your
        data.
      </p>
      <p>
        <strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any
        natural or legal person who processes the data on behalf of the Data
        Controller. We may use the services of various Service Providers in
        order to process your data more effectively.
      </p>
      <p>
        <strong>DATA SUBJECT</strong> is any living individual who is the
        subject of Personal Data.
      </p>
      <p>
        <strong>PROCESSING</strong> in relation to personal data, means any
        operation or set of operations which is performed on personal data or on
        sets of personal data (whether or not by automated means, such as
        collection, recording, organisation, structuring, storage, alteration,
        retrieval, consultation, use, disclosure, dissemination, restriction,
        erasure or destruction).
      </p>
      <p>
        <strong>THE USER</strong> is the individual using our Service. The User
        corresponds to the Data Subject, who is the subject of Personal Data.{' '}
      </p>
      <h2>3. Your data protection rights</h2>
      <p>Under data protection law, you have rights including:</p>
      <p>
        <strong>Your right of access -</strong> You have the right to ask us for
        copies of your personal information.
      </p>
      <p>
        <strong>Your right to rectification -</strong> You have the right to ask
        us to rectify personal information you think is inaccurate. You also
        have the right to ask us to complete information you think is
        incomplete.
      </p>
      <p>
        <strong>Your right to erasure -</strong> You have the right to ask us to
        erase your personal information in certain circumstances.
      </p>
      <p>
        <strong>Your right to restriction of processing -</strong> You have the
        right to ask us to restrict the processing of your personal information
        in certain circumstances.
      </p>
      <p>
        <strong>Your right to object to processing -</strong> You have the right
        to object to the processing of your personal information in certain
        circumstances.
      </p>
      <p>
        <strong>Your right to data portability -</strong> You have the right to
        ask that we transfer the personal information you gave us to another
        organisation, or to you, in certain circumstances.
      </p>
      <p>
        You are not required to pay any charge for exercising your rights. If
        you make a request, we have one month to respond to you.
      </p>
      <p>
        Please contact us at hello@commonknowledge.coop if you wish to make a
        request.
      </p>
      <h2>4. Information Collection and Use</h2>
      <p>
        <strong>4.1.</strong> We collect several different types of information
        for various purposes to provide and improve our Service to you.
      </p>
      <h2>5. Types of Data Collected</h2>
      <p>
        <strong>5.1. Personal Data</strong>
      </p>
      <p>
        While using our Service, we may ask you to provide us with certain
        personally identifiable information that can be used to contact or
        identify you (“Personal Data”). Personally identifiable information may
        include, but is not limited to:
      </p>
      <ol>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Address, Postal code, City</li>
        <li>IP Address and Cookies</li>
      </ol>
      <p>
        We may use your Personal Data to contact you with newsletters, marketing
        or promotional materials and other information that may be of interest
        to you. You may opt out of receiving any, or all, of these
        communications from us by emailing to hello@commonknowledge.coop
      </p>
      <p>
        <strong>5.2. Usage Data</strong>
      </p>
      <p>
        We may also collect information that your browser sends whenever you
        visit our Service (“Usage Data”).
      </p>
      <p>
        This Usage Data includes your computer's de-identified Internet Protocol
        address (IP address), browser type, browser version, the pages of our
        Service that you visit, the time and date of your visit, the time spent
        on those pages, unique device identifiers and other diagnostic data.
        Common Knowledge owns the intellectual property rights in the Usage
        Data.
      </p>
      <p>
        <strong>5.3. Tracking Cookies Data</strong>
      </p>
      <p>
        We use cookies and similar tracking technologies to track the activity
        on our Service and we hold certain information.
      </p>
      <p>
        Cookies are files with a small amount of data which may include an
        anonymous unique identifier. Cookies are sent to your browser from a
        website and stored on your device. Other tracking technologies are also
        used such as beacons, tags and scripts to collect and track information
        and to improve and analyse our Service.
      </p>
      <p>
        You can instruct your browser to refuse all cookies or to indicate when
        a cookie is being sent. However, if you do not accept cookies, you may
        not be able to use some portions of our Service.
      </p>
      <p>Examples of Cookies we use:</p>
      <ol>
        <li>Session Cookies: We use Session Cookies to operate our Service.</li>
        <li>
          Preference Cookies: We use Preference Cookies to remember your
          preferences and various settings.
        </li>
        <li>
          Security Cookies: We use Security Cookies for security purposes.
        </li>
      </ol>
      <h2>6. Use of Data</h2>
      <p>Common Knowledge uses the collected data for various purposes:</p>
      <ol>
        <li>to provide and maintain our Service;</li>
        <li>to notify you about changes to our Service;</li>
        <li>
          to allow you to participate in interactive features of our Service
          when you choose to do so;
        </li>
        <li>to provide customer support;</li>
        <li>
          to gather analysis or valuable information so that we can improve our
          Service;
        </li>
        <li>to monitor the usage of our Service;</li>
        <li>to detect, prevent and address technical issues;</li>
        <li>to fulfil any other purpose for which you provide it;</li>
        <li>
          to carry out our obligations and enforce our rights arising from any
          contracts entered into between you and us, including for billing and
          collection;
        </li>
        <li>
          to provide you with notices about your account and/or subscription,
          including expiration and renewal notices, email-instructions, etc.;
        </li>
        <li>
          to provide you with news, special offers and general information about
          other goods, services and events which we offer that are similar to
          those that you have already purchased or enquired about unless you
          have opted not to receive such information;
        </li>
        <li>
          in any other way we may describe when you provide the information;
        </li>
        <li>for any other purpose with your consent.</li>
      </ol>
      <h2>7. Retention of Data</h2>
      <p>
        <strong>7.1.</strong> We will retain your Personal Data only for as long
        as is necessary for the purposes set out in the Agreement and this
        Privacy Policy but no more than twelve months after the termination of
        your Account. We will retain and use your Personal Data to the extent
        necessary to comply with our legal obligations (for example, if we are
        required to retain your data to comply with applicable laws, resolve
        disputes, and enforce our legal agreements and policies).
      </p>
      <h2>8. Processing Location</h2>
      <p>
        <strong>8.1.</strong> Your consent to this Privacy Policy followed by
        your submission of such information represents your agreement to process
        the data in the United Kingdom.
      </p>
      <h2>9. Disclosure of Data</h2>
      <p>
        We may disclose personal information that we collect, or you provide:
      </p>
      <ol>
        <li>
          <strong>Disclosure for Law Enforcement.</strong> Under certain
          circumstances, we may be required to disclose your Personal Data if
          required to do so by law or in response to valid requests by public
          authorities.
        </li>
        <li>
          <strong>Business Transaction.</strong> If we or our subsidiaries are
          involved in a merger, acquisition or asset sale, your Personal Data
          may be transferred.
        </li>
        <li>
          <strong>Other cases.</strong> We may disclose your information also:
          <ol>
            <li>to our subsidiaries and affiliates;</li>
            <li>
              to contractors, service providers, and other third parties we use
              to support our business;
            </li>
            <li>to fulfil the purpose for which you provide it;</li>
            <li>
              for any other purpose disclosed by us when you provide the
              information;
            </li>
            <li>with your consent in any other cases;</li>
            <li>
              if we believe disclosure is necessary or appropriate to protect
              the rights, property, or safety of the Company, our customers, or
              others.
            </li>
          </ol>
        </li>
      </ol>
      <h2>10. Security of Data</h2>
      <p>
        The security of your data is important to us but remember that no method
        of transmission over the Internet or method of electronic storage is
        100% secure.
      </p>
      <p>
        While we strive to use commercially acceptable means to protect your
        Personal Data, we cannot guarantee its absolute security.
      </p>
      <h2>11. Service Providers</h2>
      <p>
        We may employ third party companies and individuals to facilitate our
        Service (“Service Providers”), provide Service on our behalf, perform
        Service-related services or assist us in analysing how our Service is
        used.
      </p>
      <p>
        These third parties have access to your Personal Data only to perform
        these tasks on our behalf and are obligated not to disclose or use it
        for any other purpose.
      </p>
      <h2>12. Analytics</h2>
      <p>
        We may use third-party Service Providers to monitor and analyse the use
        of the Service.
      </p>
      <p>
        <strong>12.1. Sentry.</strong> Sentry is an open-source error tracking
        solution provided by Functional Software Inc. More information is
        available here: https://sentry.io/privacy/. To opt out of Sentry
        tracking, see https://sentry.io/contact/gdpr/
      </p>
      <p>
        <strong>12.2. Posthog.</strong> Posthog is a product analytics service
        we use to capture usage data, which we use to maintain and improve the
        product.
      </p>
      <h2>13. CI/CD tools</h2>
      <p>
        We may use third-party Service Providers to automate the development
        process of our Service.
      </p>
      <p>
        <strong>13.1. GitHub.</strong> GitHub is provided by GitHub, Inc. GitHub
        is a development platform to host and review code, manage projects, and
        build software. For more information on what data GitHub collects for
        what purpose and how the protection of the data is ensured, please visit
        GitHub Privacy Policy page:
        https://help.github.com/en/articles/github-privacy-statement
      </p>
      <h2>14. Links to Other Sites</h2>
      <p>
        Our Service may contain links to other sites that are not operated by
        us. If you click a third party link, you will be directed to that third
        party's site. We strongly advise you to review the Privacy Policy of
        every site you visit.
      </p>
      <p>
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </p>
      <h2>15. Children's Privacy</h2>
      <p>
        Our Services are not intended for use by children age 13 and under for
        users in the United States, Belgium, Denmark, Portugal, Sweden and the
        United Kingdom, 14 and under in China, Spain, Bulgaria, Austria, Cyprus,
        Italy and Lithuania, 15 and under in Slovenia, Check Republic, Greece
        and France and 18 and under for India, Columbia, Indonesia, Egypt and 16
        and under all other countries (“Children”).
      </p>
      <p>
        We do not knowingly collect personally identifiable information from
        Children. If you become aware that a Child has provided us with Personal
        Data, please contact us. If we become aware that we have collected
        Personal Data from Children without verification of parental consent, we
        take steps to remove that information from our servers.
      </p>
      <h2>16. Changes to This Privacy Policy</h2>
      <p>
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page.
      </p>
      <p>
        We will let you know via email and/or a prominent notice on our Service,
        prior to the change becoming effective and update “effective date” at
        the top of this Privacy Policy.
      </p>
      <p>
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>
      <h2>16. How to complain</h2>
      <p>
        If you have any concerns about our use of your personal information, you
        can make a complaint to us at data@commonknowledge.coop
      </p>
      <p>
        You can also complain to the ICO if you are unhappy with how we have
        used your data.
      </p>
      <p>The ICO’s address:</p>
      <p>
        Information Commissioner’s Office
        <br />
        Wycliffe House
        <br />
        Water Lane
        <br />
        Wilmslow
        <br />
        Cheshire
        <br />
        SK9 5AF
      </p>
      <p>Helpline number: 0303 123 1113</p>
      <p>ICO website: https://www.ico.org.uk</p>
      <h2>17. Contact us</h2>
      <p>
        If you have any questions relating to this Privacy Policy, please
        contact: data@commonknowledge.coop
      </p>
    </div>
  )
}

export const metadata: Metadata = {
  title: 'Privacy Policy',
}
