# Generated by Django 4.1.4 on 2022-12-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsourcer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="number_part",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
