# Generated by Django 4.1 on 2022-10-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0006_increase_data_type_name_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datatype",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("date", "Date"),
                    ("boolean", "True/False"),
                    ("profile_id", "Profile Id"),
                ],
                max_length=20,
            ),
        ),
    ]
