# Generated by Django 4.1.2 on 2022-12-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0025_dataset_comparators_dataset_default_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="areadata",
            name="json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="persondata",
            name="json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("integer", "Integer"),
                    ("float", "Floating Point Number"),
                    ("percent", "Percentage"),
                    ("date", "Date"),
                    ("boolean", "True/False"),
                    ("profile_id", "Profile Id"),
                    ("json", "JSON data"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="datatype",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("integer", "Integer"),
                    ("float", "Floating Point Number"),
                    ("percent", "Percentage"),
                    ("date", "Date"),
                    ("boolean", "True/False"),
                    ("profile_id", "Profile Id"),
                    ("json", "JSON data"),
                ],
                max_length=20,
            ),
        ),
    ]
