# Generated by Django 4.1.2 on 2023-06-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0049_add_dataset_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="unit_distribution",
            field=models.TextField(
                choices=[
                    ("people_in_area", "Evenly distributed over people in an area"),
                    ("physical_area", "Evenly distributed over a physical area"),
                    ("point", "Point data (recalculated)"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="unit_type",
            field=models.TextField(
                choices=[
                    ("raw", "Raw unit (e.g. people or buildings)"),
                    ("percentage", "Percentage"),
                    ("point", "Point data (e.g. lat/long)"),
                ],
                null=True,
            ),
        ),
    ]
