#!/bin/bash

# abort on any errors
set -e

# check that we are in the expected directory
cd `dirname $0`/..

if [ ! -f .env ] ; then
    echo "==> Seeding an initial .env from .env-example..."
    cp .env-example .env

    # if INSIDE_DOCKER is set, write NATIVE to DEVENV in .env
    if [ -n "$INSIDE_DOCKER" ] ; then
        # delete line containing DEVENV from .env
        sed -i '/DEVENV/d' .env
        echo "==> Writing DEVENV=native to .env..."
        echo 'DEVENV="native"' >> .env
    fi

fi

if ! grep ^DEVENV .env ; then
    echo "DEVENV key not found in your environment."
    while [ -z "$devenv" ] ; do
        read -p 'Would you prefer to run local intelligence natively ("native") or with Docker Compose ("docker")? ' devenv
        case "$devenv" in
            native|docker)
                echo "DEVENV=${devenv}" >>.env
                ;;
            *)
                echo 'Sorry, incorrect response - please enter "native" or "docker"'
                unset devenv
                ;;
        esac
    done
fi
