#!/bin/bash

# abort on any errors
set -e

# check that we are in the expected directory
cd `dirname $0`/..

./node_modules/.bin/esbuild --bundle hub/static/js/all.js --outfile=build/js/all-out-esm.js --format=esm --minify
