#!/bin/bash

# abort on any errors
set -e

# check that we are in the expected directory
cd `dirname $0`/..

script/manage import_areas
script/manage import_mps

GENERATE_COMMANDS=$(find hub/management/commands/ -name 'generate_*' -printf '%f\n' | sed 's#[.]py##')

for COMMAND in $GENERATE_COMMANDS
do
    script/manage "$COMMAND"
done

IMPORT_COMMANDS=$(find hub/management/commands/ -name 'import_*' -printf '%f\n' | sed 's#[.]py##')

for COMMAND in $IMPORT_COMMANDS
do
    if [ "$COMMAND" != "import_areas" ] && [ "$COMMAND" != "import_mps" ]; then
        script/manage "$COMMAND"
    fi
done
