#!/bin/bash

# abort on any errors
set -e

# check that we are in the expected directory
cd `dirname $0`/..

./manage.py import_areas
./manage.py import_new_constituencies
./manage.py import_mps

COMMANDS=$(find hub/management/commands/ -name 'import_*' -printf '%f\n' | sed 's#[.]py##')

for COMMAND in $COMMANDS
do
    if [ "$COMMAND" != "import_areas" ] && [ "$COMMAND" != "import_mps" ] && [ "$COMMAND" != "import_new_constituencies" ]; then
        ./manage.py "$COMMAND"
    fi
done
