#!/bin/bash

# check that we are in the expected directory
cd `dirname $0`/..

./manage.py import_areas
./manage.py import_mps

COMMANDS=$(find hub/management/commands/ -name 'import_*' -printf '%f\n' | sed 's#[.]py##')

REQUIRED_COMMANDS=(
    "import_last_election_data"
)

for COMMAND in $COMMANDS
do
    # Exit on errors if $COMMAND is in $REQUIRED_COMMANDS (thanks ChatGPT)
    if [[ "${REQUIRED_COMMANDS[@]}" =~ "$COMMAND" ]]; then
        set -e
    fi

    if [ "$COMMAND" != "import_areas" ] && [ "$COMMAND" != "import_mps" ]; then
        ./manage.py "$COMMAND"

        if [ $? != 0 ]; then
            echo "WARN: Ignoring error in script $COMMAND"
        fi
    fi

    # Reset script to ignore errors if errors were temporarily prevented
    set +e
done
