#!/bin/bash

# Run all linting commands

# check that we are in the expected directory
cd `dirname $0`/..

script/dev-command black .
script/dev-command isort .
script/dev-command flake8 --exclude ".venv" .
