#!/bin/bash

# abort on any errors
set -e

# check that we are in the expected directory
cd `dirname $0`/..

# Run the update script
./script/bootstrap
./script/manage migrate
./script/import-all-data
