#!/bin/bash

# abort on any errors
set -e

# check that we are in the expected directory
cd `dirname $0`/..

script/bootstrap

if [ "$1" == "--coverage" ]; then
    script/dev-command coverage run --source=. --branch manage.py test
else
    script/dev-command ./manage.py test "$@"
fi
