#!/bin/bash

# abort on any errors
set -e

# check that we are in the expected directory
cd `dirname $0`/..

script/bootstrap

source .env
if [ "$DEVENV" == "docker" ] ; then
    PREFIX=""
else
    PREFIX="poetry run"
fi

if [ "$1" == "--coverage" ]; then
    $PREFIX coverage run --source=. --branch manage.py test
else
    $PREFIX ./manage.py test
fi
