# Generated by Django 4.1 on 2022-10-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mapit_id", models.CharField(max_length=30)),
                ("gss", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=200)),
                ("area_type", models.CharField(max_length=20)),
            ],
        ),
    ]
