# Generated by Django 4.1 on 2022-10-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="geometry",
            field=models.TextField(blank=True, null=True),
        ),
    ]
