# Generated by Django 4.1 on 2022-10-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0002_area_geometry"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
                ("data_type", models.CharField(max_length=20)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_type", models.CharField(max_length=10)),
                ("external_id", models.CharField(db_index=True, max_length=20)),
                ("id_type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=200)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.area"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.datatype"
                    ),
                ),
                ("data", models.CharField(max_length=200)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.person"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["external_id", "id_type"], name="hub_person_externa_08d0b5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="person",
            unique_together={("external_id", "id_type")},
        ),
    ]
