# Generated by Django 4.1 on 2022-10-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0004_area_gss_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="persondata",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
