# Generated by Django 4.1.2 on 2022-10-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0007_add_data_type_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="photo",
            field=models.ImageField(null=True, upload_to="person"),
        ),
    ]
