# Generated by Django 4.1.2 on 2022-11-01 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0008_add_person_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.CharField(max_length=200)),
                ("date", models.DateTimeField(blank=True, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.area"
                    ),
                ),
                (
                    "data_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.datatype"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
