# Generated by Django 4.1.2 on 2022-11-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0012_remove_datatype_description_remove_datatype_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datatype",
            name="average",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datatype",
            name="label",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
