# Generated by Django 4.1.2 on 2022-11-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0014_dataset_is_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="category",
            field=models.TextField(
                blank=True,
                choices=[
                    ("opinion", "Public Opinion"),
                    ("place", "Place"),
                    ("movement", "Movement"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dataset",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
