# Generated by Django 4.1.2 on 2022-11-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0017_alter_dataset_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataset",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("integer", "Integer"),
                    ("float", "Floating Point Number"),
                    ("percent", "Percentage"),
                    ("date", "Date"),
                    ("boolean", "True/False"),
                    ("profile_id", "Profile Id"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="datatype",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("integer", "Integer"),
                    ("float", "Floating Point Number"),
                    ("percent", "Percentage"),
                    ("date", "Date"),
                    ("boolean", "True/False"),
                    ("profile_id", "Profile Id"),
                ],
                max_length=20,
            ),
        ),
    ]
