# Generated by Django 4.1.2 on 2022-11-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0019_add_dataset_source_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="datatype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
