# Generated by Django 4.1.2 on 2022-11-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0020_add_data_type_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="datatype",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
