# Generated by Django 4.1.2 on 2022-12-01 11:00

from django.db import migrations, models

from hub.models import AreaData, PersonData


def data_to_num(apps, schema_editor):
    for areadata in AreaData.objects.all():
        areadata.data = areadata.data
        areadata.save()

    for persondata in PersonData.objects.all():
        persondata.data = persondata.data
        persondata.save()


def data_to_string(apps, schema_editor):
    AreaData.objects.exclude(float=None).update(data=models.F("float"))
    AreaData.objects.exclude(int=None).update(data=models.F("int"))
    PersonData.objects.exclude(float=None).update(data=models.F("float"))
    PersonData.objects.exclude(int=None).update(data=models.F("int"))


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0023_replace_number_data_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="areadata",
            name="float",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="areadata",
            name="int",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="persondata",
            name="float",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="persondata",
            name="int",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(data_to_num, data_to_string),
    ]
