# Generated by Django 4.1.2 on 2022-12-08 11:10

from django.db import migrations

mappings = {
    "constituency_ruc": {
        "Rural": "green",
        "Urban": "grey",
        "Sparse and rural": "lightgreen",
        "Urban with rural areas": "lightgrey",
    },
    "party": {
        "Alba Party": "#005EB8",
        "Alliance Party of Northern Ireland": "#F6CB2F",
        "Conservative Party": "#0087DC",
        "Democratic Unionist Party": "#D46A4C",
        "Green Party of England and Wales": "#6AB023",
        "Labour Co-operative": "#E4003B",
        "Labour Party": "#E4003B",
        "Liberal Democrats": "#FAA61A",
        "Plaid Cymru": "#005B54",
        "Scottish National Party": "#FDF38E",
        "Sinn Féin": "#326760",
        "Social Democratic and Labour Party": "#2AA82C",
        "Speaker of the House of Commons": "#DCDCDC",
        "independent politician": "#DCDCDC",
    },
}


def add_shader_colours(apps, schemaeditor):  # pragma: no cover
    DataSet = apps.get_model("hub", "DataSet")

    for name, mapping in mappings.items():
        try:
            dataset = DataSet.objects.get(name=name)
        except DataSet.DoesNotExist:
            continue
        options = dataset.options
        missing = []
        for title, colour in mapping.items():
            match = False
            for option in options:
                if type(option) is not dict:
                    continue
                if (
                    option.get("shader", None) is not None
                    and option.get("title", "") == title
                ):
                    option["shader"] = colour
                    match = True
                    break
            if not match:
                missing.append({"title": title, "shader": colour})

        options.extend(missing)
        dataset.options = options
        dataset.save()


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0027_add_dataset_min_max"),
    ]

    operations = [
        migrations.RunPython(add_shader_colours, reverse_noop),
    ]
