# Generated by Django 4.1.2 on 2023-04-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0032_userproperties"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproperties",
            name="full_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
