# Generated by Django 4.1.6 on 2023-04-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0034_userproperties_account_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproperties",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
