# Generated by Django 4.1.2 on 2023-04-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0035_userproperties_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproperties",
            name="agreed_terms",
            field=models.BooleanField(default=False),
        ),
    ]
