# Generated by Django 4.1.2 on 2023-08-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0041_alter_dataset_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("westminster_constituency", "Westminster Constituency")
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=300)),
            ],
        ),
    ]
