# Generated by Django 4.1.2 on 2023-08-03 13:39

from django.db import migrations


def create_constituency_type(apps, schema_editor):
    AreaType = apps.get_model("hub", "AreaType")
    AreaType.objects.create(
        name="2010 Parliamentary Constituency",
        code="WMC",
        area_type="Westminster Constituency",
        description="Westminster Parliamentary Constituency boundaries, as created in 2010",
    )


def remove_constituency_type(apps, schema_editor):
    AreaType = apps.get_model("hub", "AreaType")
    AreaType.objects.filter(name="2010 Parliamentary Constituency").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0042_areatype"),
    ]

    operations = [
        migrations.RunPython(
            create_constituency_type, reverse_code=remove_constituency_type
        )
    ]
