# Generated by Django 4.1.2 on 2023-08-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0043_create_2010_constituency_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="area_type",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
