# Generated by Django 4.1.2 on 2023-08-03 13:48

from django.db import migrations


def remove_current_area_types(apps, schema_editor):
    Area = apps.get_model("hub", "Area")
    for area in Area.objects.all():
        area.area_type = None
        area.save()


def add_current_area_types(apps, schema_editor):
    Area = apps.get_model("hub", "Area")
    for area in Area.objects.all():
        area.area_type = "WMC"
        area.save()


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0044_alter_area_area_type"),
    ]

    operations = [
        migrations.RunPython(
            remove_current_area_types, reverse_code=add_current_area_types
        )
    ]
