# Generated by Django 4.1.2 on 2023-08-03 13:50

from django.db import migrations


def backfill_current_area_types(apps, schema_editor):
    Area = apps.get_model("hub", "Area")
    AreaType = apps.get_model("hub", "AreaType")
    area_type = AreaType.objects.get(name="2010 Parliamentary Constituency")
    for area in Area.objects.all():
        area.area_type = area_type
        area.save()


def remove_current_area_types(apps, schema_editor):
    Area = apps.get_model("hub", "Area")
    for area in Area.objects.all():
        area.area_type = None
        area.save()


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0046_alter_area_area_type"),
    ]

    operations = [
        migrations.RunPython(
            backfill_current_area_types, reverse_code=remove_current_area_types
        )
    ]
