# Generated by Django 4.1.2 on 2023-09-05 10:52

from django.db import migrations


def update_field(apps, schemaeditor):  # pragma: no cover
    DataType = apps.get_model("hub", "DataType")
    AreaType = apps.get_model("hub", "AreaType")
    area_type = AreaType.objects.get(name="2010 Parliamentary Constituency")
    DataType.objects.filter(data_set__table="areadata").update(area_type=area_type)


def reverse(apps, schema_editor):  # pragma: no cover
    DataType = apps.get_model("hub", "DataType")
    DataType.objects.filter(data_set__table="areadata").update(area_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0053_datatype_area_type"),
    ]

    operations = [migrations.RunPython(update_field, reverse_code=reverse)]
