# Generated by Django 4.2.5 on 2023-11-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0057_populate_dataset_areas_available"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaOverlap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("population_overlap", models.SmallIntegerField(default=0)),
                ("area_overlap", models.SmallIntegerField(default=0)),
                (
                    "area_new",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_overlaps",
                        to="hub.area",
                    ),
                ),
                (
                    "area_old",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="old_overlaps",
                        to="hub.area",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="area",
            name="overlaps",
            field=models.ManyToManyField(through="hub.AreaOverlap", to="hub.area"),
        ),
    ]
