# Generated by Django 4.2.5 on 2024-01-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0058_areaoverlap_area_overlaps"),
    ]

    operations = [
        migrations.AddField(
            model_name="datatype",
            name="auto_converted",
            field=models.BooleanField(
                default=False,
                help_text="True if this has been auto converted from an area with overlapping geometry",
            ),
        ),
    ]
