# Generated by Django 4.2.5 on 2023-12-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0059_person_end_date_person_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="id_type",
            field=models.CharField(max_length=30),
        ),
    ]
