# Generated by Django 4.2.10 on 2024-02-27 12:52

from django.db import migrations
from django.contrib.auth import get_user_model
from gqlauth.models import UserStatus


def ensure_users_have_status(apps, schema_editor):
    User = get_user_model()
    users = User.objects.all()
    for user in users:
        try:
            user.status
        except User.status.RelatedObjectDoesNotExist:
            UserStatus.objects.create(user=user, verified=True)


class Migration(migrations.Migration):
    """
    The strawberry-django-auth library expects all Users to have an associated
    Status, but it doesn't create them for existing Users. This migration
    ensures that all existing Users have an "verified" Status.
    """

    dependencies = [
        ("hub", "0063_alter_areadata_data_alter_persondata_data"),
    ]

    operations = [
        migrations.RunPython(
            ensure_users_have_status, reverse_code=migrations.RunPython.noop
        ),
    ]
