# Generated by Django 4.2.10 on 2024-02-29 15:14

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("hub", "0063_alter_areadata_data_alter_persondata_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalDataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="AirtableSource",
            fields=[
                (
                    "externaldatasource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hub.externaldatasource",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="Personal access token. Requires the following 4 scopes: data.records:read, data.records:write, schema.bases:read, webhook:manage",
                        max_length=250,
                    ),
                ),
                ("base_id", models.CharField(max_length=250)),
                ("table_id", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name": "Airtable table",
            },
            bases=("hub.externaldatasource",),
        ),
        migrations.CreateModel(
            name="RemoteCSVSource",
            fields=[
                (
                    "externaldatasource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hub.externaldatasource",
                    ),
                ),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "Public CSV",
            },
            bases=("hub.externaldatasource",),
        ),
        migrations.CreateModel(
            name="ExternalDataSourceUpdateConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "postcode_column",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "mapping",
                    django_jsonform.models.fields.JSONField(blank=True, null=True),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hub.externaldatasource",
                    ),
                ),
            ],
        ),
    ]
