# Generated by Django 4.2.10 on 2024-02-19 18:01

from django.db import migrations


def mp_external_id_to_twfy(apps, schema_editor):
    PersonData = apps.get_model("hub", "PersonData")

    mps = PersonData.objects.filter(
        data_type__name="twfyid", person__id_type="parlid"
    ).select_related("person")

    for mp in mps:
        mp.person.id_type = "twfyid"
        mp.person.external_id = mp.data
        mp.person.save()


def mp_external_id_to_parlid(apps, schema_editor):
    PersonData = apps.get_model("hub", "PersonData")

    mps = PersonData.objects.filter(
        data_type__name="parlid", person__id_type="twfyid"
    ).select_related("person")

    for mp in mps:
        mp.person.id_type = "parlid"
        mp.person.external_id = mp.data
        mp.person.save()


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0063_alter_areadata_data_alter_persondata_data"),
    ]

    operations = [
        migrations.RunPython(
            mp_external_id_to_twfy, reverse_code=mp_external_id_to_parlid
        )
    ]
