# Generated by Django 4.2.10 on 2024-03-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0064_convert_mp_external_id_to_twfy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areatype",
            name="area_type",
            field=models.CharField(
                choices=[
                    ("westminster_constituency", "Westminster Constituency"),
                    ("single_tier_council", "Single Tier Council"),
                    ("district_council", "District Council"),
                ],
                max_length=50,
            ),
        ),
    ]
