# Generated by Django 4.2.10 on 2024-03-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0064_ensure_users_have_status"),
        ("hub", "0064_externaldatasource_airtablesource_remotecsvsource_and_more"),
    ]

    operations = []
