# Generated by Django 4.2.10 on 2024-03-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0064_convert_mp_external_id_to_twfy"),
        ("hub", "0064_ensure_users_have_status"),
    ]

    operations = []
