# Generated by Django 4.2.10 on 2024-03-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0065_merge_20240301_0612"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirtableWebhook",
            fields=[
                (
                    "airtable_id",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("cursor", models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
