# Generated by Django 4.2.11 on 2024-07-03 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0065_alter_areatype_area_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("person_type", models.CharField(max_length=10)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.area"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.person"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="areas",
            field=models.ManyToManyField(
                related_name="people", through="hub.PersonArea", to="hub.area"
            ),
        ),
    ]
