# Generated by Django 4.2.10 on 2024-03-05 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0065_merge_20240305_1757"),
        ("hub", "0066_airtablewebhook"),
    ]

    operations = []
