# Generated by Django 4.2.11 on 2024-07-03 09:49

from django.db import migrations


def populate_person_areas(apps, schema_editor):
    Person = apps.get_model("hub", "Person")
    PersonArea = apps.get_model("hub", "PersonArea")
    for p in Person.objects.all():
        pa = PersonArea(person=p, area=p.area, person_type=p.person_type)
        pa.save()


def reverse_noop(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0066_personarea_person_areas"),
    ]

    operations = [
        migrations.RunPython(populate_person_areas, reverse_code=reverse_noop)
    ]
