# Generated by Django 4.2.10 on 2024-03-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0067_merge_0065_merge_20240305_1757_0066_airtablewebhook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airtablewebhook",
            name="cursor",
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.DeleteModel(
            name="RemoteCSVSource",
        ),
    ]
