# Generated by Django 4.2.10 on 2024-03-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0069_organisation_externaldatasource_organisation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="externaldatasourceupdateconfig",
            old_name="data_source",
            new_name="external_data_source",
        )
    ]
