# Generated by Django 4.2.11 on 2024-07-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0069_populate_person_old_area"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="area",
        ),
    ]
