# Generated by Django 4.2.10 on 2024-03-06 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0070_remove_externaldatasourceupdateconfig_data_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaldatasourceupdateconfig",
            name="external_data_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="update_configs",
                to="hub.externaldatasource",
            ),
        ),
    ]
