# Generated by Django 4.2.10 on 2024-03-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0071_alter_externaldatasourceupdateconfig_external_data_source"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="airtablesource",
            unique_together={("base_id", "table_id", "api_key")},
        ),
    ]
