# Generated by Django 4.2.10 on 2024-03-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0072_alter_airtablesource_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externaldatasourceupdateconfig",
            name="postcode_column",
        ),
        migrations.AddField(
            model_name="externaldatasource",
            name="geography_column",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="externaldatasource",
            name="geography_column_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("postcode", "Postcode"),
                    ("ward", "Ward"),
                    ("council", "Council"),
                    ("constituency", "Constituency"),
                ],
                max_length=250,
                null=True,
            ),
        ),
    ]
