# Generated by Django 4.2.10 on 2024-03-10 11:04

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0075_alter_externaldatasource_geography_column_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldatasource",
            name="auto_import_enabled",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="externaldatasource",
            name="auto_update_enabled",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="externaldatasource",
            name="auto_update_mapping",
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="externaldatasource",
            name="geography_column",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="externaldatasource",
            name="name",
            field=models.CharField(default="Un-named data source", max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ExternalDataSourceUpdateConfig",
        ),
    ]
