# Generated by Django 4.2.20 on 2025-05-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0075_areaaction_areaactiondata"),
    ]

    operations = [
        migrations.AddField(
            model_name="areaaction",
            name="require_session",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="areaaction",
            name="passphrase",
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
    ]
