# Generated by Django 4.2.22 on 2025-06-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0076_areaaction_require_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="areadata",
            name="bool",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="persondata",
            name="bool",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
