# Generated by Django 4.2.10 on 2024-03-11 03:13

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0076_externaldatasource_autoimport_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldatasource",
            name="fields",
            field=django_jsonform.models.fields.JSONField(
                blank=True, default=[], null=True
            ),
        ),
        migrations.AlterField(
            model_name="externaldatasource",
            name="auto_update_mapping",
            field=django_jsonform.models.fields.JSONField(
                blank=True, default=[], null=True
            ),
        ),
    ]
