# Generated by Django 4.2.10 on 2024-03-11 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0077_externaldatasource_fields_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="externaldatasource",
            old_name="auto_update_mapping",
            new_name="update_mapping",
        ),
    ]
