# Generated by Django 4.2.22 on 2025-07-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("hub", "0078_sitedataset_dataset_sites"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproperties",
            name="sites",
            field=models.ManyToManyField(to="sites.site"),
        ),
    ]
