# Generated by Django 4.2.22 on 2025-07-31 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("hub", "0079_userproperties_sites"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAreaType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "areatype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.areatype"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="areatype",
            name="sites",
            field=models.ManyToManyField(through="hub.SiteAreaType", to="sites.site"),
        ),
    ]
