# Generated by Django 4.2.22 on 2025-08-26 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("hub", "0080_siteareatype_areatype_sites"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAreaAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.areaaction"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="areaaction",
            name="sites",
            field=models.ManyToManyField(through="hub.SiteAreaAction", to="sites.site"),
        ),
    ]
