# Generated by Django 4.2.22 on 2025-09-01 10:14

from django.conf import settings
from django.db import migrations


def reverse_noop(apps, schema_editor):  # pragma: no cover
    pass


def create_default_site(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    host = settings.ALLOWED_HOSTS[0]
    if host == "*":
        return

    site_count = Site.objects.count()
    if site_count == 0:
        Site.objects.create(
            name="default",
            domain=host,
        )
    elif site_count == 1 and Site.objects.filter(domain="example.com").exists():
        Site.objects.filter(domain="example.com").update(name="default", domain="host")


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0081_siteareaaction_areaaction_sites"),
    ]

    operations = [migrations.RunPython(create_default_site, reverse_noop)]
