# Generated by Django 4.2.10 on 2024-03-12 14:50

from django.db import migrations
import django_choices_field.fields
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0081_genericdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaldatasource",
            name="geography_column_type",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("postcode", "Postcode"),
                    ("ward", "Ward"),
                    ("admin_district", "Council"),
                    ("parliamentary_constituency", "Constituency"),
                    ("parliamentary_constituency_2025", "Constituency (2024)"),
                ],
                choices_enum=hub.models.ExternalDataSource.PostcodesIOGeographyTypes,
                default="postcode",
                max_length=31,
            ),
        ),
    ]
