# Generated by Django 4.2.22 on 2025-09-01 10:15

from django.db import migrations

from hub.site_utils import add_site_to_classes


def reverse_noop(apps, schema_editor):  # pragma: no cover
    pass


def add_site_to_everything(apps, schema_editor):
    Site = apps.get_model("sites", "Site")

    if Site.objects.count() == 1:
        site = Site.objects.first()

        classes = []
        for c in ["AreaAction", "AreaType", "DataSet", "UserProperties"]:
            classes.append(apps.get_model("hub", c))

        add_site_to_classes(site, classes)


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0082_create_default_site"),
    ]

    operations = [migrations.RunPython(add_site_to_everything, reverse_noop)]
