# Generated by Django 4.2.11 on 2025-10-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0084_areatype_names_singular_plural"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="mapit_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
