# Generated by Django 4.2.10 on 2024-03-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0084_report_mapreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapreport",
            name="layers",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
