# Generated by Django 4.2.10 on 2024-03-16 12:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0085_mapreport_layers"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericdata",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="genericdata",
            name="polygon",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
