# Generated by Django 4.2.11 on 2025-10-04 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0085_alter_area_mapit_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="areaoverlap",
            old_name="area_old",
            new_name="area_from",
        ),
        migrations.RenameField(
            model_name="areaoverlap",
            old_name="area_new",
            new_name="area_to",
        ),
    ]
