# Generated by Django 4.2.25 on 2025-11-06 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0086_rename_areaoverlap_old_new_from_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areaoverlap",
            name="area_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overlaps_from",
                to="hub.area",
            ),
        ),
        migrations.AlterField(
            model_name="areaoverlap",
            name="area_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overlaps_to",
                to="hub.area",
            ),
        ),
        migrations.AlterField(
            model_name="areatype",
            name="area_type",
            field=models.CharField(
                choices=[
                    ("westminster_constituency", "Westminster Constituency"),
                    ("single_tier_council", "Single Tier Council"),
                    ("district_council", "District Council"),
                    ("policing_area", "Policing Area"),
                ],
                max_length=50,
            ),
        ),
    ]
