# Generated by Django 4.2.10 on 2024-03-18 15:58

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0086_genericdata_point_genericdata_polygon"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericdata",
            name="postcode_data",
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
    ]
