# Generated by Django 4.2.10 on 2024-03-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0086_genericdata_point_genericdata_polygon"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailchimpSource",
            fields=[
                (
                    "externaldatasource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hub.externaldatasource",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(help_text="Mailchimp API key.", max_length=250),
                ),
                (
                    "list_id",
                    models.CharField(
                        help_text="The unique identifier for the Mailchimp list.",
                        max_length=250,
                    ),
                ),
                (
                    "member_email",
                    models.EmailField(
                        help_text="Email for member to fetch.", max_length=250
                    ),
                ),
            ],
            options={
                "verbose_name": "Mailchimp list",
                "unique_together": {("list_id", "api_key")},
            },
            bases=("hub.externaldatasource",),
        ),
    ]
