# Generated by Django 4.2.10 on 2024-03-18 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0087_mailchimpsource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailchimpsource",
            name="member_email",
        ),
    ]
