# Generated by Django 4.2.10 on 2024-03-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0088_area_point_area_polygon_alter_genericdata_polygon"),
        ("hub", "0088_remove_mailchimpsource_member_email"),
    ]

    operations = []
