# Generated by Django 4.2.10 on 2024-03-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0089_externaldatasource_address_field_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericdata",
            name="address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="genericdata",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="genericdata",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="genericdata",
            name="full_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="genericdata",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="genericdata",
            name="phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="genericdata",
            name="postcode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
