# Generated by Django 4.2.10 on 2024-03-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0090_genericdata_address_genericdata_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericdata",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="genericdata",
            name="address",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="genericdata",
            name="email",
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="genericdata",
            name="first_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="genericdata",
            name="full_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="genericdata",
            name="last_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
