# Generated by Django 4.2.10 on 2024-03-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0092_alter_area_area_type_alter_areadata_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hub.area"
            ),
        ),
        migrations.AlterField(
            model_name="persondata",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hub.person"
            ),
        ),
    ]
