# Generated by Django 4.2.10 on 2024-03-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0091_remove_mailchimpsource_member_email"),
        ("hub", "0093_alter_person_area_alter_persondata_person"),
    ]

    operations = []
