# Generated by Django 4.2.10 on 2024-03-28 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0093_alter_person_area_alter_persondata_person"),
        ("hub", "0094_rename_sharing_permissions_externaldatasource_orgs_with_access"),
    ]

    operations = []
