# Generated by Django 4.2.10 on 2024-03-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0095_merge_20240328_1835"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapreport",
            name="display_options",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
