# Generated by Django 4.2.10 on 2024-03-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0096_mapreport_display_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="gss",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
