# Generated by Django 4.2.10 on 2024-04-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0096_alter_genericdata_postcode"),
        ("hub", "0097_alter_area_gss"),
    ]

    operations = []
