# Generated by Django 4.2.10 on 2024-04-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0098_merge_20240403_1137"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["gss"], name="hub_area_gss_635fb0_idx"),
        ),
    ]
