# Generated by Django 4.2.10 on 2024-04-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0094_merge_20240328_1119"),
        ("hub", "0099_area_hub_area_gss_635fb0_idx"),
    ]

    operations = []
