# Generated by Django 4.2.11 on 2024-04-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0065_alter_areatype_area_type"),
        ("hub", "0101_apitoken"),
    ]

    operations = []
