# Generated by Django 4.2.10 on 2024-04-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0102_auto_20240417_1319"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="airtablesource",
            unique_together={("base_id", "table_id", "encrypted_api_key")},
        ),
    ]
