# Generated by Django 4.2.11 on 2024-04-26 20:05

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0102_merge_0065_alter_areatype_area_type_0101_apitoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionNetworkSource",
            fields=[
                (
                    "externaldatasource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hub.externaldatasource",
                    ),
                ),
                (
                    "api_key",
                    django_cryptography.fields.encrypt(
                        models.CharField(max_length=250, unique=True)
                    ),
                ),
            ],
            options={
                "verbose_name": "Action Network list",
            },
            bases=("hub.externaldatasource",),
        ),
    ]
