# Generated by Django 4.2.10 on 2024-04-17 13:51

from django.db import migrations
import hub.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0103_alter_airtablesource_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airtablesource",
            name="encrypted_api_key",
            field=hub.fields.EncryptedCharField(
                blank=True,
                help_text="Personal access token. Requires the following 4 scopes: data.records:read, data.records:write, schema.bases:read, webhook:manage",
                max_length=250,
                null=True,
            ),
        ),
    ]
