# Generated by Django 4.2.10 on 2024-04-17 14:36

from django.db import migrations
import hub.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0104_alter_airtablesource_encrypted_api_key"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="airtablesource",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="airtablesource",
            name="api_key",
        ),
        migrations.RenameField(
            model_name="airtablesource",
            old_name="encrypted_api_key",
            new_name="api_key",
        ),
        migrations.AlterUniqueTogether(
            name="airtablesource",
            unique_together={("base_id", "table_id", "api_key")},
        ),
    ]
