# Generated by Django 4.2.10 on 2024-04-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0105_alter_airtablesource_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailchimpsource",
            name="api_key",
        ),
        migrations.RenameField(
            model_name="mailchimpsource",
            old_name="encrypted_api_key",
            new_name="api_key",
        ),
    ]
