# Generated by Django 4.2.10 on 2024-04-17 14:49

from django.db import migrations
import hub.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0106_remove_mailchimpsource_encrypted_api_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailchimpsource",
            name="api_key",
            field=hub.fields.EncryptedCharField(
                blank=True, help_text="Mailchimp API key.", max_length=250, null=True
            ),
        ),
    ]
