# Generated by Django 4.2.11 on 2024-05-09 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0102_merge_0065_alter_areatype_area_type_0101_apitoken"),
        ("hub", "0107_alter_mailchimpsource_api_key"),
    ]

    operations = []
