# Generated by Django 4.2.11 on 2024-05-09 23:38

from django.db import migrations
import hub.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0108_merge_20240509_2322"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="token_new",
            field=hub.fields.EncryptedCharField(
                default="default_value",
                max_length=1500
            )
        )
    ]
