# Generated by Django 4.2.11 on 2024-05-09 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0109_apitoken_token_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apitoken",
            name="token",
        ),
        migrations.RenameField(
            model_name="apitoken",
            old_name="token_new",
            new_name="token",
        ),
    ]
