# Generated by Django 4.2.11 on 2024-05-24 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0103_report_public"),
        ("hub", "0110_remove_apitoken_token_new_alter_apitoken_token"),
    ]

    operations = []
