# Generated by Django 4.2.11 on 2024-05-10 00:28

from django.db import migrations, models
import django.db.models.deletion
import hub.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0110_remove_apitoken_token_new_alter_apitoken_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionNetworkSource",
            fields=[
                (
                    "externaldatasource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hub.externaldatasource",
                    ),
                ),
                ("api_key", hub.fields.EncryptedCharField(max_length=250, unique=True)),
            ],
            options={
                "verbose_name": "Action Network list",
            },
            bases=("hub.externaldatasource",),
        ),
    ]
