# Generated by Django 4.2.11 on 2024-05-24 15:13

from django.db import migrations
from django.db.models.functions import Upper
import django_choices_field.fields
import hub.models


def uppercase_datatype(apps, schema_editor):
    ExternalDataSource = apps.get_model("hub", "ExternalDataSource")

    ExternalDataSource.objects.update(data_type=Upper("data_type"))


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0111_actionnetworksource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaldatasource",
            name="data_type",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("MEMBER", "Members or supporters"),
                    ("REGION", "Areas or regions"),
                    ("OTHER", "Other"),
                ],
                choices_enum=hub.models.ExternalDataSource.DataSourceType,
                default="OTHER",
                max_length=6,
            ),
        ),
        migrations.RunPython(uppercase_datatype),
    ]
