# Generated by Django 4.2.11 on 2024-05-25 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0093_uploadedfile"),
        ("hub", "0112_alter_externaldatasource_data_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubContentPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("puck_json_content", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HubHomepage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "custom_domain",
                    models.CharField(
                        blank=True,
                        help_text="The custom domain for the microsite.",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("layers", models.JSONField(blank=True, default=list, null=True)),
                ("puck_json_content", models.JSONField(blank=True, default=dict)),
                ("nav_links", models.JSONField(blank=True, default=list, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hubs",
                        to="hub.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
