# Generated by Django 4.2.11 on 2024-05-26 21:32

from django.db import migrations, models
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0112_hubcontentpage_hubhomepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hubcontentpage",
            name="puck_json_content",
            field=models.JSONField(
                blank=True, default=hub.models.generate_puck_json_content
            ),
        ),
    ]
