# Generated by Django 4.2.11 on 2024-05-27 17:58

from django.db import migrations, models
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0114_remove_hubhomepage_custom_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hubhomepage",
            name="puck_json_content",
            field=models.JSONField(
                blank=True, default=hub.models.generate_puck_json_content
            ),
        ),
    ]
