# Generated by Django 4.2.11 on 2024-05-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0098_externaldatasource_description_field_and_more"),
        ("hub", "0114_remove_hubhomepage_custom_domain"),
    ]

    operations = []
