# Generated by Django 4.2.11 on 2024-05-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0115_alter_mailchimpsource_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaldatasource",
            name="deduplication_hash",
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
