# Generated by Django 4.2.11 on 2024-05-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0117_alter_area_gss"),
    ]

    operations = []
