# Generated by Django 4.2.11 on 2024-05-28 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0118_merge_20240528_1234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hubhomepage",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hubs",
                to="hub.organisation",
            ),
        ),
    ]
