# Generated by Django 4.2.10 on 2024-04-02 08:11

from django.db import migrations, models
import django_choices_field.fields
import django_jsonform.models.fields
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0119_alter_hubhomepage_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldatasource",
            name="description_field",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="externaldatasource",
            name="end_time_field",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="externaldatasource",
            name="image_field",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="externaldatasource",
            name="public_url_field",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="externaldatasource",
            name="start_time_field",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="externaldatasource",
            name="title_field",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="genericdata",
            name="description",
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name="genericdata",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genericdata",
            name="image",
            field=models.ImageField(null=True, upload_to="generic_data"),
        ),
        migrations.AddField(
            model_name="genericdata",
            name="osm_data",
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genericdata",
            name="public_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="genericdata",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genericdata",
            name="title",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="label",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="source",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="datatype",
            name="label",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="externaldatasource",
            name="data_type",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("member", "Members or supporters"),
                    ("region", "Areas or regions"),
                    ("event", "Events"),
                    ("location", "Locations"),
                    ("story", "Stories"),
                    ("other", "Other"),
                ],
                choices_enum=hub.models.ExternalDataSource.DataSourceType,
                default="other",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=500),
        ),
    ]
