# Generated by Django 4.2.11 on 2024-05-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0116_externaldatasource_can_display_details_publicly_and_more"),
        ("hub", "0121_alter_area_name_alter_externaldatasource_data_type_and_more"),
    ]

    operations = []
