# Generated by Django 4.2.11 on 2024-06-03 01:20

from django.db import migrations, models
import django.db.models.deletion
import hub.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0125_hubhomepage_google_analytics_tag_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketTailorSource",
            fields=[
                (
                    "externaldatasource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hub.externaldatasource",
                    ),
                ),
                ("api_key", hub.fields.EncryptedCharField(max_length=250)),
            ],
            options={
                "verbose_name": "Ticket Tailor event list",
            },
            bases=("hub.externaldatasource",),
        ),
    ]
