# Generated by Django 4.2.11 on 2024-06-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0126_tickettailorsource"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tickettailorsource",
            options={"verbose_name": "Ticket Tailor box office"},
        ),
    ]
