# Generated by Django 4.2.11 on 2024-06-05 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0126_actionnetworksource_group_name"),
        ("hub", "0127_alter_tickettailorsource_options"),
    ]

    operations = []
