# Generated by Django 4.2.11 on 2024-06-10 17:36

from django.db import migrations, models
import django_jsonform.models.fields
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0129_alter_externaldatasource_geography_column_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldatasource",
            name="countries",
            field=models.JSONField(
                blank=True,
                default=hub.models.default_countries,
                help_text="ISO 3166-1 alpha-2 country codes for geocoding addresses.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="genericdata",
            name="mapbox_geocode_data",
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
    ]
