# Generated by Django 4.2.11 on 2024-06-10 20:00

from django.db import migrations, models
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0129_alter_externaldatasource_geography_column_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genericdata",
            old_name="postcode_data",
            new_name="geocode_data",
        ),
        migrations.RemoveField(
            model_name="genericdata",
            name="osm_data",
        ),
        migrations.AddField(
            model_name="externaldatasource",
            name="countries",
            field=models.JSONField(
                blank=True,
                default=hub.models.default_countries,
                help_text="ISO 3166-1 alpha-2 country codes for geocoding addresses.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="genericdata",
            name="geocoder",
            field=models.CharField(
                blank=True,
                default=hub.models.Geocoder["POSTCODES_IO"].value,
                max_length=1000,
                null=True,
            ),
        ),
    ]
