# Generated by Django 4.2.11 on 2024-06-13 21:24

from django.db import migrations, models
import django.db.models.deletion
import hub.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0131_alter_userproperties_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditableGoogleSheetsSource",
            fields=[
                (
                    "externaldatasource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hub.externaldatasource",
                    ),
                ),
                (
                    "credentials",
                    hub.fields.EncryptedTextField(
                        blank=True, max_length=750, null=True
                    ),
                ),
                ("spreadsheet_id", models.CharField(max_length=250)),
                ("sheet_name", models.CharField(max_length=100)),
                ("id_field", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Editable google sheet",
            },
            bases=("hub.externaldatasource",),
        ),
    ]
