# Generated by Django 4.2.11 on 2024-06-20 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0132_alter_membership_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hubhomepage",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hubs",
                to="hub.organisation",
            ),
        ),
    ]
