# Generated by Django 4.2.11 on 2024-06-15 11:14

from django.db import migrations
import hub.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0132_editablegooglesheetssource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editablegooglesheetssource",
            name="credentials",
            field=hub.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
