# Generated by Django 4.2.11 on 2024-06-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0133_alter_hubhomepage_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubhomepage",
            name="custom_css",
            field=models.TextField(blank=True, null=True),
        ),
    ]
