# Generated by Django 4.2.11 on 2024-06-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0133_alter_editablegooglesheetssource_credentials"),
    ]

    operations = [
        migrations.RenameField(
            model_name="editablegooglesheetssource",
            old_name="credentials",
            new_name="oauth_credentials",
        ),
    ]
