# Generated by Django 4.2.11 on 2024-06-20 15:56

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0134_hubhomepage_custom_css"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubhomepage",
            name="primary_colour",
            field=wagtail_color_panel.fields.ColorField(
                blank=True, max_length=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="hubhomepage",
            name="secondary_colour",
            field=wagtail_color_panel.fields.ColorField(
                blank=True, max_length=7, null=True
            ),
        ),
    ]
