# Generated by Django 4.2.11 on 2024-06-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0132_alter_membership_role"),
        ("hub", "0134_rename_credentials_editablegooglesheetssource_oauth_credentials"),
    ]

    operations = []
