# Generated by Django 4.2.11 on 2024-06-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0135_hubhomepage_primary_colour_and_more"),
        ("hub", "0135_merge_20240617_1430"),
    ]

    operations = []
