# Generated by Django 4.2.11 on 2024-08-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0138_genericdata_created_at_organisation_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldatasource",
            name="can_display_point_field",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="genericdata",
            name="can_display_point",
            field=models.BooleanField(default=True),
        ),
    ]
