# Generated by Django 4.2.11 on 2024-09-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0140_genericdata_social_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldatasource",
            name="social_url_field",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
