# Generated by Django 4.2.11 on 2024-12-10 14:25

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0142_alter_hubhomepage_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldatasource",
            name="geography_config",
            field=django_jsonform.models.fields.JSONField(
                blank=True, default=list, null=True
            ),
        ),
    ]
