# Generated by Django 4.2.11 on 2024-12-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0143_alter_externaldatasource_data_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubimage",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="description"
            ),
        ),
    ]
