# Generated by Django 4.2.11 on 2024-12-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0144_hubimage_description"),
    ]

    operations = [
        # Noop:
        migrations.RunSQL(sql=migrations.RunSQL.noop)
    ]
