# Generated by Django 4.2.11 on 2024-12-12 16:48

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0144_hubimage_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalJSONSource",
            fields=[
                (
                    "externaldatasource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hub.externaldatasource",
                    ),
                ),
                (
                    "data",
                    django_jsonform.models.fields.JSONField(blank=True, default=list),
                ),
                ("id_field", models.CharField(default="id", max_length=250)),
            ],
            options={
                "verbose_name": "Test source",
            },
            bases=("hub.externaldatasource",),
        ),
    ]
