# Generated by Django 4.2.11 on 2024-12-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0144_hubimage_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="mapit_type",
            field=models.CharField(db_index=True, blank=True, null=True, max_length=30),
        ),
    ]
