# Generated by Django 4.2.11 on 2024-12-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0147_externaldatasource_geography_config"),
        ("hub", "0148_area_mapit_type"),
    ]

    operations = []
