# Generated by Django 4.2.11 on 2024-12-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0148_area_mapit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="mapit_all_names",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
