# Generated by Django 4.2.11 on 2024-12-10 14:25

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0149_area_mapit_all_names"),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        migrations.AddField(
            model_name="externaldatasource",
            name="geocoding_config",
            field=django_jsonform.models.fields.JSONField(
                blank=True, default=list, null=True
            ),
        ),
    ]
