# Generated by Django 4.2.11 on 2024-12-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0147_batchrequest_send_email_batchrequest_sent_email_and_more"),
        ("hub", "0149_area_mapit_all_names"),
    ]

    operations = []
