# Generated by Django 4.2.11 on 2024-12-10 14:25

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0149_merge_20241217_1742"),
    ]

    operations = [TrigramExtension(), UnaccentExtension()]