# Generated by Django 4.2.11 on 2025-01-30 15:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import hub.restricted_file_field.fields
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0152_genericdata_area_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedCSVSource",
            fields=[
                (
                    "externaldatasource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hub.externaldatasource",
                    ),
                ),
                (
                    "spreadsheet_file",
                    hub.restricted_file_field.fields.SafeFileField(
                        upload_to="uploaded_data_sources"
                    ),
                ),
                ("id_field", models.TextField()),
                ("delimiter", models.TextField(blank=True, default=",")),
                (
                    "columns",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Uploaded CSV file",
            },
            bases=("hub.externaldatasource",),
        ),
        # Disable due to bugs
        migrations.CreateModel(
            name="DatabaseJSONSource",
            fields=[
                (
                    "externaldatasource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hub.externaldatasource",
                    ),
                ),
                (
                    "data",
                    django_jsonform.models.fields.JSONField(blank=True, default=list),
                ),
                ("id_field", models.CharField(default="id", max_length=250)),
            ],
            options={"verbose_name": "Database JSON source"},
            bases=("hub.externaldatasource",),
        ),
    ]
