# Generated by Django 4.2.11 on 2025-01-31 14:17

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0154_remove_externaldatasource_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldatasource",
            name="field_definitions",
            field=django_jsonform.models.fields.JSONField(
                blank=True, default=list, null=True
            ),
        ),
    ]
