# Generated by Django 4.2.11 on 2025-02-06 13:01

from django.db import migrations, models
import django.utils.timezone
import django_choices_field.fields
import hub.models
import utils.django_json


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0155_externaldatasource_field_definitions"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="batchrequest",
            name="is_cancelled_by_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="batchrequest",
            name="type",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("Import", "Import"), ("Update", "Update")],
                choices_enum=hub.models.BatchRequest.BatchRequestType,
                default="Import",
                max_length=6,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="batchrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="areadata",
            name="json",
            field=models.JSONField(
                blank=True, encoder=utils.django_json.DBJSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="genericdata",
            name="json",
            field=models.JSONField(
                blank=True, encoder=utils.django_json.DBJSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="persondata",
            name="json",
            field=models.JSONField(
                blank=True, encoder=utils.django_json.DBJSONEncoder, null=True
            ),
        ),
    ]
