# Generated by Django 4.2.11 on 2025-02-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0156_batchrequest_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchrequest",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batch_requests",
                to="hub.externaldatasource",
            ),
        ),
    ]
