# Generated by Django 4.2.11 on 2025-02-08 01:11

from django.db import migrations
import hub.models
import hub.restricted_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0157_batchrequest_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedcsvsource",
            name="spreadsheet_file",
            field=hub.restricted_file_field.fields.SafeFileField(
                upload_to=hub.models.UploadedCSVSource.org_directory_path
            ),
        ),
    ]
