# Generated by Django 4.2.11 on 2025-02-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0158_alter_genericdata_unique_together"),
        ("hub", "0158_alter_uploadedcsvsource_spreadsheet_file"),
    ]

    operations = []
