# Generated by Django 4.2.11 on 2025-02-11 13:17

from django.db import migrations, models
import hub.models
import hub.storage


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0159_merge_20250210_1038"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=hub.storage.OverwriteStorage(),
                upload_to=hub.models.Report.report_image_path,
            ),
        ),
    ]
