# Generated by Django 4.2.11 on 2025-02-10 15:58

from django.db import migrations, models
import utils.django_json


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0159_merge_20250210_1038"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericdata",
            name="parsed_json",
            field=models.JSONField(
                blank=True, encoder=utils.django_json.DBJSONEncoder, null=True
            ),
        ),
    ]
