# Generated by Django 4.2.11 on 2025-02-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0159_merge_20250210_1038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericdata",
            name="can_display_point",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
