# Generated by Django 4.2.11 on 2025-02-11 22:01

import django.core.validators
from django.db import migrations, models
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0160_alter_genericdata_can_display_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedcsvsource",
            name="spreadsheet_file",
            field=models.FileField(
                upload_to=hub.models.UploadedCSVSource.org_directory_path,
                validators=[django.core.validators.FileExtensionValidator(("csv",))],
            ),
        ),
    ]
