# Generated by Django 4.2.11 on 2025-02-11 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0160_report_cover_image"),
        ("hub", "0161_alter_uploadedcsvsource_spreadsheet_file"),
    ]

    operations = []
