# Generated by Django 4.2.11 on 2025-02-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0161_externaldatasource_last_materialized"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldatasource",
            name="last_import",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
