# Generated by Django 4.2.11 on 2025-02-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0162_externaldatasource_last_import"),
        ("hub", "0162_merge_20250211_2218"),
    ]

    operations = []
