# Generated by Django 4.2.11 on 2025-02-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0163_merge_20250214_1409"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedcsvsource",
            name="use_row_number_as_id",
            field=models.BooleanField(default=False),
        ),
    ]
